### ISSUE TITLE
RPS End game does not show correct weapon

### ISSUE THREAD

**Issue by Breadpaw** [ManonLef/Rock-Paper-Scissors-plus-UI#1]
The prompt message in the end game of the RPS game does not reflect your weapon of choice, it looks like it randomly chooses your weapon (which you didn't choose)

**Comment by ManonLef** [comment]
Hi @Breadpaw you're absolutely correct. Would you like me to assign this issue to you while I work on my 2022 version? 

You could look into pull requests and basic formatting as well. It will be nice practice. Basically you can do a PR and format it so that it states which issue it will resolve (which is the one you just opened). 

Let me know if I can assign it okay :)

**Comment by Breadpaw** [comment]
Yes please. Such an interesting opportunity.
